import Head from 'next/head'
import Image from 'next/image'
import Layout from '../components/common/layout'
import Comment from '../components/home/Comment'
import Button from '../components/home/Button'
import { css } from '@emotion/react'

const styles = {
  /* -----  ホームページ  ----- */

  container: css`
    width: 100%;
    min-height: 100vh;
    overflow: hidden;
    position: relative;
  `,

  /* タイトル */
  bg_title: css`
    position: absolute;
    top: 60px;
    right: 0;
  `,

  titleBox: css`
    position: absolute;
    top: 60px;
    right: 80px;
    flex: 1;
    padding: 0 5px;
  `,

  title: css`
    font-size: 3.2rem;
    text-align: center;
  `,

  subtitle: css`
    font-size: 1.1rem;
    text-align: center;
  `,

  /* ----- レイアウト ----- */

  layoutContainer: css`
    display: flex;
  `,

  /* コメント */
  commentContainer: css`
    height: 100vh;
    display: flex;
    flex: 1;
    justify-content: center;
    align-content: center;
    align-items: center;
  `,

  /* ボタン */
  btnContainer: css`
    height: 100vh;
    display: flex;
    flex: 1;
    align-items: center;
  `,
};

export default function Home() {

  return (
    <Layout>
      <div css={styles.container}>
        <Head>
          <title>Flacha App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Image
          src="/images/bg_title.png"
          width={400}
          height={120}
          alt={'タイトル背景'}
          css={styles.bg_title}
        />
        <header css={styles.titleBox}>
          <h1 css={styles.title}>Flacha</h1>
          <h2 css={styles.subtitle}>スパチャフラッシュ暗算</h2>
        </header>

        <div css={styles.layoutContainer}>
          {/* 左にコメント 右にボタン */}

          <div css={styles.commentContainer}>
            <Comment/>
          </div>
          <div css={styles.btnContainer}>
            <Button/>
          </div>
        </div>
      </div>
    </Layout>
  )
}
