import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import Layout from '../components/common/layout'

export default function Home() {
  return (
    <Layout>
      <div className={styles.container}>
        <Head>
          <title>Flacha App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <header className={styles.titleBox}>
          <h1 className={styles.title}>Flacha</h1>
          <h2 className={styles.subtitle}>スパチャフラッシュ暗算</h2>
        </header>

        <main className={styles.main}>
          <Link href="Flash" className={styles.flash} scroll={false}>
            <div>
              フラッシュモード
            </div>
          </Link>
          <Link href="Chat" className={styles.chat} scroll={false}>
            <div>
              チャットモード
            </div>
          </Link>
        </main>
      </div>
    </Layout>
  )
}
